/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package apotek;

import java.sql.Connection;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author user
 */
public class FormPembayaran extends javax.swing.JFrame {
    int harga_obat = 0;
    int stokBarang = 0;
    int id_obat = 0;
    double total_harga = 0;
    double uang_keluar = 0;
    private String username;
    
    public void setUsername(String username){
        this.username = username;
    }
    
    private void tampilkan_data() {
    DefaultTableModel model = new DefaultTableModel();
    model.addColumn("No.");
    model.addColumn("Nama Obat");
    model.addColumn("Harga Obat");
    model.addColumn("Stok Obat");
    
    try {
        String sql = "SELECT id_obat, nama_obat, harga_obat, stok_barang FROM penjualan";
        java.sql.Connection conn = (Connection) ConfigDB.config();
        java.sql.Statement stm = conn.createStatement();
        java.sql.ResultSet res = stm.executeQuery(sql);
        
        while (res.next()) {
            model.addRow(new Object[]{
                res.getString("id_obat"),
                res.getString("nama_obat"),
                res.getString("harga_obat"),
                res.getString("stok_barang"),
            });
        }
        tblPembayaran.setModel(model);
    } catch (SQLException e) {
        System.out.println("Error: " + e.getMessage());
    }
}
    
    private void kosongkan_data(){
        fieldJumlah.setText("0");
        fieldKodeDiskon.setText("");
        fieldBayar.setText("0");
        
        txtHarga.setText("Rp. 0");
        txtPotonganHarga.setText("Rp. 0");
        txtTotalHarga.setText("Rp. 0");
        txtNamaObat.setText("(nama)");
        txtStok.setText("(stok)");
        txtKembalian.setText("Rp. 0");
        harga_obat = 0;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    public FormPembayaran() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtNama = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPembayaran = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btnStruk = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        btnBatal = new javax.swing.JButton();
        btnHitung = new javax.swing.JButton();
        btnBeli = new javax.swing.JButton();
        fieldJumlah = new javax.swing.JTextField();
        fieldKodeDiskon = new javax.swing.JTextField();
        txtNamaObat = new javax.swing.JLabel();
        txtStok = new javax.swing.JLabel();
        txtHarga = new javax.swing.JLabel();
        txtPotonganHarga = new javax.swing.JLabel();
        txtTotalHarga = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        txtBayar = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        fieldBayar = new javax.swing.JTextField();
        txtKembalian = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(0, 204, 102));

        jLabel2.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 36)); // NOI18N
        jLabel2.setText("Pembayaran");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(242, 242, 242))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(14, 14, 14))
        );

        jLabel3.setText("Nama pegawai:");

        txtNama.setText("(Nama Pegawai)");

        tblPembayaran.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblPembayaran.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPembayaranMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblPembayaran);

        jLabel5.setText("Nama Obat  :");

        jLabel6.setText("Stok             :");

        jLabel7.setText("Jumlah                 :");

        jLabel8.setText("Kode diskon        :");

        jLabel9.setText("Harga          :");

        btnStruk.setBackground(new java.awt.Color(0, 204, 51));
        btnStruk.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 14)); // NOI18N
        btnStruk.setText("Struk");
        btnStruk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStrukActionPerformed(evt);
            }
        });

        jLabel10.setText("Potongan Harga  :");

        jLabel11.setText("Total Harga            :");

        btnBatal.setBackground(new java.awt.Color(0, 204, 51));
        btnBatal.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 14)); // NOI18N
        btnBatal.setText("Batal");
        btnBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatalActionPerformed(evt);
            }
        });

        btnHitung.setBackground(new java.awt.Color(0, 204, 51));
        btnHitung.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 14)); // NOI18N
        btnHitung.setText("Hitung Harga");
        btnHitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHitungActionPerformed(evt);
            }
        });

        btnBeli.setBackground(new java.awt.Color(0, 204, 51));
        btnBeli.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 14)); // NOI18N
        btnBeli.setText("Beli");
        btnBeli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBeliActionPerformed(evt);
            }
        });

        fieldJumlah.setText("0");

        txtNamaObat.setText("(nama)");

        txtStok.setText("(Stok)");

        txtHarga.setText("Rp.0");

        txtPotonganHarga.setText("Rp.0");

        txtTotalHarga.setText("Rp.0");

        jLabel18.setText("Bayar                       :");

        jLabel20.setText("Kembalian               :");

        fieldBayar.setText("0");

        txtKembalian.setText("Rp.0");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtStok, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtNamaObat, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
                                    .addComponent(txtHarga, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(98, 98, 98)
                                .addComponent(btnBatal, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(23, 23, 23)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(fieldKodeDiskon, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)
                                    .addComponent(fieldJumlah, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)
                                    .addComponent(txtPotonganHarga, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel20, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(fieldBayar, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtBayar, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(txtTotalHarga, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtKembalian, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnHitung, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(41, 41, 41)
                                .addComponent(btnBeli, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(51, 51, 51)
                                .addComponent(btnStruk, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(81, 81, 81))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 651, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtNama))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel7)
                    .addComponent(fieldJumlah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNamaObat)
                    .addComponent(jLabel11)
                    .addComponent(txtTotalHarga))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel8)
                    .addComponent(fieldKodeDiskon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtStok)
                    .addComponent(jLabel18)
                    .addComponent(txtBayar)
                    .addComponent(fieldBayar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtPotonganHarga)
                    .addComponent(jLabel20)
                    .addComponent(jLabel9)
                    .addComponent(txtHarga)
                    .addComponent(txtKembalian))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnHitung, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBeli, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBatal, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnStruk, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnHitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHitungActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
        boolean promo = false;

        int jumlah_dibeli = Integer.parseInt(fieldJumlah.getText());
        int uang_masuk = Integer.parseInt(fieldBayar.getText());

        if(jumlah_dibeli >= 0 && stokBarang != 0){
            if(fieldKodeDiskon.getText().equals("sehat")){
                promo = true;
            }

            total_harga = harga_obat * jumlah_dibeli;

            txtHarga.setText("Rp. " + total_harga);
            
            uang_keluar = uang_masuk - total_harga;
            
            txtKembalian.setText("Rp. " + uang_keluar);
            

            if(promo){
                txtPotonganHarga.setText("RP. " + total_harga*0.20);
                total_harga = total_harga - total_harga*0.20;
                uang_keluar = uang_masuk - total_harga;
                txtKembalian.setText("Rp. " + uang_keluar);
            }
            txtTotalHarga.setText("Rp. " + total_harga);
        }
    }//GEN-LAST:event_btnHitungActionPerformed

    private void btnBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalActionPerformed
        // TODO add your handling code here:
        FormMenu formMenu = new FormMenu();
            formMenu.setVisible(true);
            this.dispose();
    }//GEN-LAST:event_btnBatalActionPerformed

    private void btnBeliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBeliActionPerformed
           // TODO add your handling code here:
        try {
        int jumlah_dibeli = Integer.parseInt(fieldJumlah.getText());
        int uang_masuk = Integer.parseInt(fieldBayar.getText());
        int total = (int) total_harga;

        if (stokBarang >= jumlah_dibeli) {
            if (uang_masuk >= total) {
                java.sql.Connection coon = (Connection) ConfigDB.config();

                // Update stok barang
                String sql = "UPDATE penjualan SET stok_barang = ? WHERE id_obat = ?";
                java.sql.PreparedStatement pstm = coon.prepareStatement(sql);
                pstm.setInt(1, stokBarang - jumlah_dibeli);
                pstm.setInt(2, id_obat);
                pstm.executeUpdate();

                // Hitung uang kembalian
                uang_masuk -= total;
                fieldBayar.setText(Integer.toString(uang_masuk));

                tampilkan_data();
                kosongkan_data();
                JOptionPane.showMessageDialog(null, "Sukses!");
            } else {
                JOptionPane.showMessageDialog(null, "Saldo tidak mencukupi!");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Stok barang tidak cukup!");
        }
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, e.getMessage());
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Masukkan angka yang valid!");
    }
    }//GEN-LAST:event_btnBeliActionPerformed

    private void tblPembayaranMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPembayaranMouseClicked
        // TODO add your handling code here:
        int baris = tblPembayaran.rowAtPoint(evt.getPoint());
    
        // Ambil data dari setiap kolom pada baris yang diklik
        String id = tblPembayaran.getValueAt(baris, 0).toString(); // Kolom ID Obat
        id_obat = Integer.parseInt(id); // Simpan ID ke variabel id_barang

        String obat = tblPembayaran.getValueAt(baris, 1).toString(); // Kolom Nama Obat
        txtNamaObat.setText(obat); // Tampilkan Nama Obat

        String stokString = tblPembayaran.getValueAt(baris, 3).toString(); // Kolom Stok Barang
        stokBarang = Integer.parseInt(stokString); // Simpan Stok ke variabel stokBarang
        txtStok.setText(stokString); // Tampilkan Stok

        String hargaString = tblPembayaran.getValueAt(baris, 2).toString(); // Kolom Harga Obat
        harga_obat = Integer.parseInt(hargaString); // Simpan Harga ke variabel harga_barang 
        txtHarga.setText("Rp. " + harga_obat);
        // Set field jumlah default ke 1
        fieldJumlah.setText("1");

    }//GEN-LAST:event_tblPembayaranMouseClicked

    private void btnStrukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStrukActionPerformed
        int jumlah_dibeli = Integer.parseInt(fieldJumlah.getText());
        int uang_masuk = Integer.parseInt(fieldBayar.getText());
        
          JOptionPane.showMessageDialog(this, 
            "======= STRUK PEMBAYARAN =======\n" +
            "Nama Obat: " + txtNamaObat.getText() + "\n" +
            "Jumlah: " + jumlah_dibeli + "\n" +
            "Total Harga: Rp." + total_harga + "\n" +
            "Bayar: Rp." + uang_masuk + "\n" +
            "Kembalian: Rp." + uang_keluar, 
            "Struk Pembayaran", JOptionPane.INFORMATION_MESSAGE);
    


    }//GEN-LAST:event_btnStrukActionPerformed

    /**
     * @param args the command line arguments
     */
    public FormPembayaran(String username){
       this.username = username;
       initComponents();
       tampilkan_data();
       txtNama.setText(username);
   }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBatal;
    private javax.swing.JButton btnBeli;
    private javax.swing.JButton btnHitung;
    private javax.swing.JButton btnStruk;
    private javax.swing.JTextField fieldBayar;
    private javax.swing.JTextField fieldJumlah;
    private javax.swing.JTextField fieldKodeDiskon;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblPembayaran;
    private javax.swing.JLabel txtBayar;
    private javax.swing.JLabel txtHarga;
    private javax.swing.JLabel txtKembalian;
    private javax.swing.JLabel txtNama;
    private javax.swing.JLabel txtNamaObat;
    private javax.swing.JLabel txtPotonganHarga;
    private javax.swing.JLabel txtStok;
    private javax.swing.JLabel txtTotalHarga;
    // End of variables declaration//GEN-END:variables
}
